spring:
  mail:
    from: tiennguyen2283@gmail.com
    host: smtp.gmail.com
    port: 587
    username: tiennguyen2283@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/home_service
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secretKey:


bankHub:
  clientId :
  secretKey :
  url: https://sandbox.bankhub.dev
  link: https://dev.link.bankhub.dev


payOS:
  clientId :
  apiKey:
  checkSumKey:


vietQr:
  clientId :
  apiKey : 

upload:
  dir: /var/www/uploads
#  dir: D:/larkEWA/uploads

server:
  forward-headers-strategy: framework

admin:
  username: admin
  password: 123456